CREATE DATABASE [ContagemVeiculos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContagemVeiculos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ContagemVeiculos.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContagemVeiculos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ContagemVeiculos_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [ContagemVeiculos] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [ContagemVeiculos] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET ARITHABORT OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [ContagemVeiculos] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ContagemVeiculos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ContagemVeiculos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ContagemVeiculos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ContagemVeiculos] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ContagemVeiculos] SET  READ_WRITE 
GO
ALTER DATABASE [ContagemVeiculos] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ContagemVeiculos] SET  MULTI_USER 
GO
ALTER DATABASE [ContagemVeiculos] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ContagemVeiculos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ContagemVeiculos] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ContagemVeiculos]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ContagemVeiculos] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


USE [ContagemVeiculos]
GO

/****** Object:  Table [dbo].[veiculos_rastreados]    Script Date: 04/06/2026 13:36:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[veiculos_rastreados](
	[id] INT IDENTITY(1,1) PRIMARY KEY,
	[track_id] [int] NOT NULL,
	[classe] [nchar](20) NOT NULL,
	[placa] [nchar](10) NULL
) ON [PRIMARY]
GO

